

# Site Settings
title: 						"ichadhr"
email: 						"ichadhr@gmail.com"
description: 				"Naturally and artificially flavoured."
baseurl: 					""
url: 						"https://ichadhr.github.io"
logourl: 					"/assets/img/bloglogo.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"ichadhr"
author_url: 				""
author_bio: 				"It's okay to eat fish because they don't have any feelings."
author_email: 				"ichadhr@gmail.com"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"https://twitter.com/ichadhr"
facebook_url: 				""
github_url:  				"https://github.com/ichadhr"
youtube_url:  				""
dribbble_url:  				""
googleplus_url: 			""
instagram_url:  			""
pinterest_url:  			""
linkedin_url:  				""


# Theme Settings
theme_disqus_shortname: 	""
theme_google_comments: 		false
theme_analytics_id: 		""
theme_analytics_domain: 	""
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
sass:
 sass_dir: "assets/css/"
 style: :compressed

# Timezone
timezone: Asia/Jakarta

# Build Settings
markdown: 					kramdown
permalink: 					/post/:year/:title

# Gems Plugin
gems:
    ['jekyll-paginate', 'jekyll-gist', 'kramdown', 'rouge']